<?xml version="1.0"?>

<!DOCTYPE config [
        <!ELEMENT config (virtualType|type)*>
        <!ATTLIST config
                xmlns:xsi CDATA #REQUIRED
                xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
        <!ELEMENT virtualType (arguments)*>
        <!ATTLIST virtualType
                name CDATA #REQUIRED
                type CDATA #REQUIRED>
        <!ELEMENT arguments (argument)*>
        <!ELEMENT argument (item)*>
        <!ATTLIST argument
                name CDATA #REQUIRED
                xsi:type CDATA #REQUIRED>
        <!ELEMENT item (item)*>
        <!ATTLIST item
                name CDATA #REQUIRED
                xsi:type CDATA #REQUIRED>
        <!ELEMENT type (arguments)*>
        <!ATTLIST type
                name CDATA #REQUIRED>
        ]>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">

    <virtualType name="customLogger" type="Magento\Framework\Logger\Monolog">
        <arguments>
            <argument name="handlers"  xsi:type="array">
                <item name="debug" xsi:type="object">Firebear\ImportExport\Logger\Handler</item>
            </argument>
        </arguments>
    </virtualType>

    <type name="Firebear\PlatformM1\Logger\Handler">
        <arguments>
            <argument name="logger" xsi:type="object">customLogger</argument>
        </arguments>
    </type>

    <type name="Magento\Framework\Console\CommandListInterface">
        <arguments>
            <argument name="commands" xsi:type="array">
                <item name="migrationJobCommand" xsi:type="object">Firebear\PlatformM1\Console\Command\MigrationJobCommand</item>
            </argument>
        </arguments>
    </type>

    <!-- Shipment Entity -->
    <virtualType name="Firebear\ImportExport\Model\Migration\ShipmentEntity" type="Firebear\ImportExport\Model\Migration\Job\General">
        <arguments>
            <argument name="sourceTable" xsi:type="string">sales_flat_shipment</argument>
            <argument name="destinationTable" xsi:type="string">sales_shipment</argument>
            <argument name="deltaMigration" xsi:type="array">
                <item name="active" xsi:type="boolean">true</item>
            </argument>
            <argument name="sourceFields" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="store_id" xsi:type="string">store_id</item>
                <item name="total_weight" xsi:type="string">total_weight</item>
                <item name="total_qty" xsi:type="string">total_qty</item>
                <item name="email_sent" xsi:type="string">email_sent</item>
                <item name="order_id" xsi:type="string">order_id</item>
                <item name="customer_id" xsi:type="string">customer_id</item>
                <item name="shipping_address_id" xsi:type="string">shipping_address_id</item>
                <item name="billing_address_id" xsi:type="string">billing_address_id</item>
                <item name="shipment_status" xsi:type="string">shipment_status</item>
                <item name="increment_id" xsi:type="string">increment_id</item>
                <item name="created_at" xsi:type="string">created_at</item>
                <item name="updated_at" xsi:type="string">updated_at</item>
                <item name="packages" xsi:type="string">packages</item>
                <item name="shipping_label" xsi:type="string">shipping_label</item>
            </argument>
            <argument name="destinationFields" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="store_id" xsi:type="string">store_id</item>
                <item name="total_weight" xsi:type="string">total_weight</item>
                <item name="total_qty" xsi:type="string">total_qty</item>
                <item name="email_sent" xsi:type="string">email_sent</item>
<!--                <item name="email_send" xsi:type="string">email_send</item>-->
                <item name="order_id" xsi:type="string">order_id</item>
                <item name="customer_id" xsi:type="string">customer_id</item>
                <item name="shipping_address_id" xsi:type="string">shipping_address_id</item>
                <item name="billing_address_id" xsi:type="string">billing_address_id</item>
                <item name="shipment_status" xsi:type="string">shipment_status</item>
                <item name="increment_id" xsi:type="string">increment_id</item>
                <item name="created_at" xsi:type="string">created_at</item>
                <item name="updated_at" xsi:type="string">updated_at</item>
                <item name="packages" xsi:type="string">packages</item>
                <item name="shipping_label" xsi:type="string">shipping_label</item>
                <item name="customer_note" xsi:type="string">customer_note</item>
                <item name="customer_note_notify" xsi:type="string">customer_note_notify</item>
            </argument>
            <argument name="fieldMapping" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="store_id" xsi:type="string">store_id</item>
                <item name="total_weight" xsi:type="string">total_weight</item>
                <item name="total_qty" xsi:type="string">total_qty</item>
                <item name="email_sent" xsi:type="string">email_sent</item>
                <item name="order_id" xsi:type="string">order_id</item>
                <item name="customer_id" xsi:type="string">customer_id</item>
                <item name="shipping_address_id" xsi:type="string">shipping_address_id</item>
                <item name="billing_address_id" xsi:type="string">billing_address_id</item>
                <item name="shipment_status" xsi:type="string">shipment_status</item>
                <item name="increment_id" xsi:type="string">increment_id</item>
                <item name="created_at" xsi:type="string">created_at</item>
                <item name="updated_at" xsi:type="string">updated_at</item>
                <item name="packages" xsi:type="string">packages</item>
                <item name="shipping_label" xsi:type="string">shipping_label</item>
            </argument>
            <argument name="sourceFilters" xsi:type="array">
                <item name="store_id" xsi:type="object">Firebear\ImportExport\Model\Migration\FilterJobs\StoreId</item>
            </argument>
            <argument name="fieldJobs" xsi:type="array">
                <item name="store_id" xsi:type="object">Firebear\ImportExport\Model\Migration\Field\Job\MapStoreId</item>
            </argument>
<!--            <argument name="postJobs" xsi:type="array">-->
<!--                <item name="sequence" xsi:type="object">Firebear\ImportExport\Model\Migration\PostJob\MagentoShipmentSequence</item>-->
<!--            </argument>-->
        </arguments>
    </virtualType>

    <!-- Insert data to the sequence_shipment_{{store_id}} table -->
    <virtualType name="Firebear\ImportExport\Model\Migration\PostJob\MagentoShipmentSequence" type="Firebear\ImportExport\Model\Migration\PostJob\SalesSequence">
        <arguments>
            <argument name="table" xsi:type="string">sales_shipment</argument>
            <argument name="entityType" xsi:type="string">shipment</argument>
        </arguments>
    </virtualType>

    <!-- Shipment Comment Entity -->
    <virtualType name="Firebear\ImportExport\Model\Migration\ShipmentCommentEntity" type="Firebear\ImportExport\Model\Migration\Job\General">
        <arguments>
            <argument name="sourceTable" xsi:type="string">sales_flat_shipment_comment</argument>
            <argument name="destinationTable" xsi:type="string">sales_shipment_comment</argument>
            <argument name="deltaMigration" xsi:type="array">
                <item name="active" xsi:type="boolean">true</item>
            </argument>
            <argument name="sourceFields" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="parent_id" xsi:type="string">parent_id</item>
                <item name="is_customer_notified" xsi:type="string">is_customer_notified</item>
                <item name="is_visible_on_front" xsi:type="string">is_visible_on_front</item>
                <item name="comment" xsi:type="string">comment</item>
                <item name="created_at" xsi:type="string">created_at</item>
            </argument>
            <argument name="destinationFields" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="parent_id" xsi:type="string">parent_id</item>
                <item name="is_customer_notified" xsi:type="string">is_customer_notified</item>
                <item name="is_visible_on_front" xsi:type="string">is_visible_on_front</item>
                <item name="comment" xsi:type="string">comment</item>
                <item name="created_at" xsi:type="string">created_at</item>
            </argument>
            <argument name="fieldMapping" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="parent_id" xsi:type="string">parent_id</item>
                <item name="is_customer_notified" xsi:type="string">is_customer_notified</item>
                <item name="is_visible_on_front" xsi:type="string">is_visible_on_front</item>
                <item name="comment" xsi:type="string">comment</item>
                <item name="created_at" xsi:type="string">created_at</item>
            </argument>
        </arguments>
    </virtualType>

    <!-- Shipment Grid Entity -->
    <virtualType name="Firebear\ImportExport\Model\Migration\ShipmentGridEntity" type="Firebear\ImportExport\Model\Migration\Job\General">
        <arguments>
            <argument name="sourceTable" xsi:type="string">sales_flat_shipment_grid</argument>
            <argument name="destinationTable" xsi:type="string">sales_shipment_grid</argument>
            <argument name="deltaMigration" xsi:type="array">
                <item name="active" xsi:type="boolean">true</item>
            </argument>
            <argument name="sourceFields" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="store_id" xsi:type="string">store_id</item>
                <item name="total_qty" xsi:type="string">total_qty</item>
                <item name="order_id" xsi:type="string">order_id</item>
                <item name="shipment_status" xsi:type="string">shipment_status</item>
                <item name="increment_id" xsi:type="string">increment_id</item>
                <item name="order_increment_id" xsi:type="string">order_increment_id</item>
                <item name="created_at" xsi:type="string">created_at</item>
                <item name="order_created_at" xsi:type="string">order_created_at</item>
                <item name="shipping_name" xsi:type="string">shipping_name</item>
            </argument>
            <argument name="destinationFields" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="store_id" xsi:type="string">store_id</item>
                <item name="total_qty" xsi:type="string">total_qty</item>
                <item name="order_id" xsi:type="string">order_id</item>
                <item name="shipment_status" xsi:type="string">shipment_status</item>
                <item name="increment_id" xsi:type="string">increment_id</item>
                <item name="order_increment_id" xsi:type="string">order_increment_id</item>
                <item name="created_at" xsi:type="string">created_at</item>
                <item name="updated_at" xsi:type="string">updated_at</item>
                <item name="order_created_at" xsi:type="string">order_created_at</item>
                <item name="customer_name" xsi:type="string">customer_name</item>
                <item name="order_status" xsi:type="string">order_status</item>
                <item name="billing_address" xsi:type="string">billing_address</item>
                <item name="shipping_address" xsi:type="string">shipping_address</item>
                <item name="shipping_name" xsi:type="string">shipping_name</item>
                <item name="billing_name" xsi:type="string">billing_name</item>
                <item name="customer_email" xsi:type="string">customer_email</item>
                <item name="customer_group_id" xsi:type="string">customer_group_id</item>
                <item name="payment_method" xsi:type="string">payment_method</item>
                <item name="shipping_information" xsi:type="string">shipping_information</item>
            </argument>
            <argument name="fieldMapping" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="store_id" xsi:type="string">store_id</item>
                <item name="total_qty" xsi:type="string">total_qty</item>
                <item name="order_id" xsi:type="string">order_id</item>
                <item name="shipment_status" xsi:type="string">shipment_status</item>
                <item name="increment_id" xsi:type="string">increment_id</item>
                <item name="order_increment_id" xsi:type="string">order_increment_id</item>
                <item name="created_at" xsi:type="string">created_at</item>
                <item name="updated_at" xsi:type="string">updated_at</item>
                <item name="order_created_at" xsi:type="string">order_created_at</item>
                <item name="customer_name" xsi:type="string">customer_name</item>
                <item name="order_status" xsi:type="string">order_status</item>
                <item name="billing_address" xsi:type="string">billing_address</item>
                <item name="shipping_address" xsi:type="string">shipping_address</item>
                <item name="shipping_name" xsi:type="string">shipping_name</item>
                <item name="billing_name" xsi:type="string">billing_name</item>
                <item name="customer_email" xsi:type="string">customer_email</item>
                <item name="customer_group_id" xsi:type="string">customer_group_id</item>
                <item name="payment_method" xsi:type="string">payment_method</item>
                <item name="shipping_information" xsi:type="string">shipping_information</item>
            </argument>
            <argument name="sourceJoins" xsi:type="array">
                <item name="sales_shipment" xsi:type="array">
                    <item name="table" xsi:type="string">sales_flat_shipment</item>
                    <item name="condition" xsi:type="string">sales_shipment.entity_id = sales_flat_shipment_grid.entity_id</item>
                    <item name="fields" xsi:type="array">
                        <item name="updated_at" xsi:type="string">updated_at</item>
                    </item>
                </item>
                <item name="sales_order" xsi:type="array">
                    <item name="table" xsi:type="string">sales_flat_order</item>
                    <item name="condition" xsi:type="string">sales_order.entity_id = sales_flat_shipment_grid.order_id</item>
                    <item name="fields" xsi:type="array">
                        <item name="customer_email" xsi:type="string">customer_email</item>
                        <item name="customer_group_id" xsi:type="string">customer_group_id</item>
                        <item name="shipping_information" xsi:type="string">shipping_description</item>
                        <item name="order_status" xsi:type="string">status</item>
                        <item name="customer_name" xsi:type="object">Firebear\ImportExport\Model\Migration\ColumnAggregator\Sales\CustomerNameAggregator</item>
                    </item>
                </item>
                <item name="payment_method" xsi:type="array">
                    <item name="table" xsi:type="string">sales_flat_order_payment</item>
                    <item name="condition" xsi:type="string">payment_method.parent_id = sales_flat_shipment_grid.order_id</item>
                    <item name="fields" xsi:type="array">
                        <item name="payment_method" xsi:type="string">method</item>
                    </item>
                </item>
                <item name="shipping_address" xsi:type="array">
                    <item name="table" xsi:type="string">sales_flat_order_address</item>
                    <item name="condition" xsi:type="string">shipping_address.entity_id = sales_shipment.shipping_address_id</item>
                    <item name="fields" xsi:type="array">
                        <item name="shipping_address" xsi:type="object">Firebear\ImportExport\Model\Migration\ColumnAggregator\Sales\ShippingAddressAggregator</item>
                        <item name="shipping_name" xsi:type="object">Firebear\ImportExport\Model\Migration\ColumnAggregator\Sales\ShippingNameAggregator</item>
                    </item>
                </item>
                <item name="billing_address" xsi:type="array">
                    <item name="table" xsi:type="string">sales_flat_order_address</item>
                    <item name="condition" xsi:type="string">billing_address.entity_id = sales_shipment.billing_address_id</item>
                    <item name="fields" xsi:type="array">
                        <item name="billing_address" xsi:type="object">Firebear\ImportExport\Model\Migration\ColumnAggregator\Sales\BillingAddressAggregator</item>
                        <item name="billing_name" xsi:type="object">Firebear\ImportExport\Model\Migration\ColumnAggregator\Sales\BillingNameAggregator</item>
                    </item>
                </item>
            </argument>
            <argument name="sourceFilters" xsi:type="array">
                <item name="sales_flat_shipment_grid.store_id" xsi:type="object">Firebear\ImportExport\Model\Migration\FilterJobs\StoreId</item>
            </argument>
            <argument name="fieldJobs" xsi:type="array">
                <item name="store_id" xsi:type="object">Firebear\ImportExport\Model\Migration\Field\Job\MapStoreId</item>
            </argument>
        </arguments>
    </virtualType>

    <virtualType name="Firebear\ImportExport\Model\Migration\ColumnAggregator\Sales\BillingAddressAggregator" type="Magento\Framework\DB\Sql\ConcatExpression">
        <arguments>
            <argument name="columns" xsi:type="array">
                <item name="company" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">billing_address</item>
                    <item name="columnName" xsi:type="string">company</item>
                </item>
                <item name="street" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">billing_address</item>
                    <item name="columnName" xsi:type="string">street</item>
                </item>
                <item name="city" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">billing_address</item>
                    <item name="columnName" xsi:type="string">city</item>
                </item>
                <item name="region" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">billing_address</item>
                    <item name="columnName" xsi:type="string">region</item>
                </item>
                <item name="postcode" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">billing_address</item>
                    <item name="columnName" xsi:type="string">postcode</item>
                </item>
            </argument>
            <argument name="separator" xsi:type="string">, </argument>
        </arguments>
    </virtualType>

    <virtualType name="Firebear\ImportExport\Model\Migration\ColumnAggregator\Sales\ShippingAddressAggregator" type="Magento\Framework\DB\Sql\ConcatExpression">
        <arguments>
            <argument name="columns" xsi:type="array">
                <item name="company" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">shipping_address</item>
                    <item name="columnName" xsi:type="string">company</item>
                </item>
                <item name="street" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">shipping_address</item>
                    <item name="columnName" xsi:type="string">street</item>
                </item>
                <item name="city" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">shipping_address</item>
                    <item name="columnName" xsi:type="string">city</item>
                </item>
                <item name="region" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">shipping_address</item>
                    <item name="columnName" xsi:type="string">region</item>
                </item>
                <item name="postcode" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">shipping_address</item>
                    <item name="columnName" xsi:type="string">postcode</item>
                </item>
            </argument>
            <argument name="separator" xsi:type="string">, </argument>
        </arguments>
    </virtualType>

    <virtualType name="Firebear\ImportExport\Model\Migration\ColumnAggregator\Sales\ShippingNameAggregator" type="Magento\Framework\DB\Sql\ConcatExpression">
        <arguments>
            <argument name="columns" xsi:type="array">
                <item name="firstname" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">shipping_address</item>
                    <item name="columnName" xsi:type="string">firstname</item>
                </item>
                <item name="lastname" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">shipping_address</item>
                    <item name="columnName" xsi:type="string">lastname</item>
                </item>
            </argument>
        </arguments>
    </virtualType>
    <virtualType name="Firebear\ImportExport\Model\Migration\ColumnAggregator\Sales\BillingNameAggregator" type="Magento\Framework\DB\Sql\ConcatExpression">
        <arguments>
            <argument name="columns" xsi:type="array">
                <item name="firstname" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">billing_address</item>
                    <item name="columnName" xsi:type="string">firstname</item>
                </item>
                <item name="lastname" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">billing_address</item>
                    <item name="columnName" xsi:type="string">lastname</item>
                </item>
            </argument>
        </arguments>
    </virtualType>

    <virtualType name="Firebear\ImportExport\Model\Migration\ColumnAggregator\Sales\CustomerNameAggregator" type="Magento\Framework\DB\Sql\ConcatExpression">
        <arguments>
            <argument name="columns" xsi:type="array">
                <item name="customer_firstname" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">sales_order</item>
                    <item name="columnName" xsi:type="string">customer_firstname</item>
                </item>
                <item name="customer_lastname" xsi:type="array">
                    <item name="tableAlias" xsi:type="string">sales_order</item>
                    <item name="columnName" xsi:type="string">customer_lastname</item>
                </item>
            </argument>
        </arguments>
    </virtualType>

    <!-- Shipment Item Entity -->
    <virtualType name="Firebear\ImportExport\Model\Migration\ShipmentItemEntity" type="Firebear\ImportExport\Model\Migration\Job\General">
        <arguments>
            <argument name="sourceTable" xsi:type="string">sales_flat_shipment_item</argument>
            <argument name="destinationTable" xsi:type="string">sales_shipment_item</argument>
            <argument name="deltaMigration" xsi:type="array">
                <item name="active" xsi:type="boolean">true</item>
                <item name="link" xsi:type="array">
                    <item name="field" xsi:type="string">parent_id</item>
                    <item name="linkField" xsi:type="string">entity_id</item>
                    <item name="linkTable" xsi:type="string">sales_flat_shipment</item>
                </item>
            </argument>
            <argument name="sourceFields" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="parent_id" xsi:type="string">parent_id</item>
                <item name="row_total" xsi:type="string">row_total</item>
                <item name="price" xsi:type="string">price</item>
                <item name="weight" xsi:type="string">weight</item>
                <item name="qty" xsi:type="string">qty</item>
                <item name="product_id" xsi:type="string">product_id</item>
                <item name="order_item_id" xsi:type="string">order_item_id</item>
                <item name="additional_data" xsi:type="string">additional_data</item>
                <item name="description" xsi:type="string">description</item>
                <item name="name" xsi:type="string">name</item>
                <item name="sku" xsi:type="string">sku</item>
            </argument>
            <argument name="destinationFields" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="parent_id" xsi:type="string">parent_id</item>
                <item name="row_total" xsi:type="string">row_total</item>
                <item name="price" xsi:type="string">price</item>
                <item name="weight" xsi:type="string">weight</item>
                <item name="qty" xsi:type="string">qty</item>
                <item name="product_id" xsi:type="string">product_id</item>
                <item name="order_item_id" xsi:type="string">order_item_id</item>
                <item name="additional_data" xsi:type="string">additional_data</item>
                <item name="description" xsi:type="string">description</item>
                <item name="name" xsi:type="string">name</item>
                <item name="sku" xsi:type="string">sku</item>
            </argument>
            <argument name="fieldMapping" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="parent_id" xsi:type="string">parent_id</item>
                <item name="row_total" xsi:type="string">row_total</item>
                <item name="price" xsi:type="string">price</item>
                <item name="weight" xsi:type="string">weight</item>
                <item name="qty" xsi:type="string">qty</item>
                <item name="product_id" xsi:type="string">product_id</item>
                <item name="order_item_id" xsi:type="string">order_item_id</item>
                <item name="additional_data" xsi:type="string">additional_data</item>
                <item name="description" xsi:type="string">description</item>
                <item name="name" xsi:type="string">name</item>
                <item name="sku" xsi:type="string">sku</item>
            </argument>
        </arguments>
    </virtualType>

    <!-- Shipment Item Entity -->
    <virtualType name="Firebear\ImportExport\Model\Migration\ShipmentTrackEntity" type="Firebear\ImportExport\Model\Migration\Job\General">
        <arguments>
            <argument name="sourceTable" xsi:type="string">sales_flat_shipment_track</argument>
            <argument name="destinationTable" xsi:type="string">sales_shipment_track</argument>
            <argument name="deltaMigration" xsi:type="array">
                <item name="active" xsi:type="boolean">true</item>
            </argument>
            <argument name="sourceFields" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="parent_id" xsi:type="string">parent_id</item>
                <item name="order_id" xsi:type="string">order_id</item>
                <item name="track_number" xsi:type="string">track_number</item>
                <item name="weight" xsi:type="string">weight</item>
                <item name="qty" xsi:type="string">qty</item>
                <item name="description" xsi:type="string">description</item>
                <item name="title" xsi:type="string">title</item>
                <item name="carrier_code" xsi:type="string">carrier_code</item>
                <item name="created_at" xsi:type="string">created_at</item>
                <item name="updated_at" xsi:type="string">updated_at</item>
            </argument>
            <argument name="destinationFields" xsi:type="array">
                <item name="entity_id" xsi:type="string">entity_id</item>
                <item name="parent_id" xsi:type="string">parent_id</item>
                <item name="order_id" xsi:type="string">order_id</item>
                <item name="track_number" xsi:type="string">track_number</item>
                <item name="weight" xsi:type="string">weight</item>
                <item name="qty" xsi:type="string">qty</item>
                <item name="description" xsi:type="string">description</item>
                <item name="title" xsi:type="string">title</item>
                <item name="carrier_code" xsi:type="string">carrier_code</item>